# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Shane Tu's Website
subtitle: CC 20', Illinois Law 25'
description: This is the personal website of Shane Tu
author: Charlotte
email: xiaodan9377@gmail.com
avatar: assets/images/head.jpeg

# You'll want to customize url and baseurl for your own site:
url: "https://shanetu1997.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url:
github_url:
stackoverflow_url:
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics: G-K6JEDQ1YCP

# The following settings are NECESSARY for the Prologue theme to run:
remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
